import 'package:flutter/material.dart';

// list is from a GitHub user but I forgot the name. Thanks to who made this list!

List fooda = [

            {"foodName":"Chicken Burrito", "foodType":"Burrito", "protein":"chicken", "price":975},
            {"foodName":"Steak Burrito", "foodType":"Burrito", "protein":"steak", "price":945},
            {"foodName":"Carnitas Burrito", "foodType":"Burrito", "protein":"carnitas", "price":1005},
            {"foodName":"Barbacoa Burrito", "foodType":"Burrito", "protein":"barbacoa", "price":965},
            {"foodName":"Chorizo Burrito", "foodType":"Burrito", "protein":"chorizo", "price":1095},
            {"foodName":"Sofritas Burrito", "foodType":"Burrito", "protein":"sofritas", "price":945},
            {"foodName":"Chicken Burrito Bowl", "foodType":"Burrito Bowl", "price":630},
            {"foodName":"Chicken Bowl", "price":630},
            {"foodName":"Steak Burrito Bowl", "foodType":"Burrito Bowl", "price":600},
            {"foodName":"Steak Bowl", "price":600},
            {"foodName":"Carnitas Burrito Bowl", "foodType":"Burrito Bowl", "price":660},
            {"foodName":"Carnitas Bowl", "price":660},
            {"foodName":"Barbacoa Burrito Bowl", "foodType":"Burrito Bowl", "price":620},
            {"foodName":"Barbacoa Bowl", "price":620},
            {"foodName":"Chorizo Burrito Bowl", "foodType":"Burrito Bowl", "price":750},
            {"foodName":"Chorizo Bowl", "price":750},
            {"foodName":"Sofritas Burrito Bowl", "foodType":"Burrito Bowl", "price":600},
            {"foodName":"Sofritas Bowl", "price":600},
            {"foodName":"Chicken Corn Tortilla Taco", "foodType":"Taco", "protein":"chicken", "price":650},
            {"foodName":"Chicken Flour Tortilla Taco", "foodType":"Taco", "protein":"chicken", "price":700},
            {"foodName":"Steak Corn Tortilla Taco", "foodType":"Taco", "protein":"steak", "price":620},
            {"foodName":"Steak Flour Tortilla Taco", "foodType":"Taco", "protein":"steak", "price":670},
            {"foodName":"Carnitas Corn Tortilla Taco", "foodType":"Taco", "protein":"carnitas", "price":680},
            {"foodName":"Carnitas Flour Tortilla Taco", "foodType":"Taco", "protein":"carnitas", "price":730},
            {"foodName":"Barbacoa Corn Tortilla Taco", "foodType":"Taco", "protein":"barbacoa", "price":640},
            {"foodName":"Barbacoa Flour Tortilla Taco", "foodType":"Taco", "protein":"barbacoa", "price":690},
            {"foodName":"Chorizo Corn Tortilla Taco", "foodType":"Taco", "protein":"chorizo", "price":770},
            {"foodName":"Chorizo Flour Tortilla Taco", "foodType":"Taco", "protein":"chorizo", "price":820},
            {"foodName":"Sofritas Corn Tortilla Taco", "foodType":"Taco", "protein":"sofritas", "price":620},
            {"foodName":"Sofritas Flour Tortilla Taco", "foodType":"Taco", "protein":"sofritas", "price":670},
            {"foodName":"Chicken Salad", "price":345,"foodType":"Salad", "sideItem":true, "dressingItem":true },
            {"foodName":"Steak Salad", "price":315, "foodType":"Salad", "sideItem":true, "dressingItem":true },
            {"foodName":"Carnitas Salad", "price":375, "foodType":"Salad", "sideItem":true, "dressingItem":true },
            {"foodName":"Barbacoa Salad", "price":335, "foodType":"Salad", "sideItem":true, "dressingItem":true },
            {"foodName":"Chorizo Salad", "price":465, "foodType":"Salad", "sideItem":true, "dressingItem":true },
	    {"foodName":"Chicken Quesadilla", "price":610, "foodType":"Quesadilla"},
            {"foodName":"Steak Quesadilla", "price":550, "foodType":"Quesadilla"},
            {"foodName":"Carnitas Quesadilla", "price":640, "foodType":"Quesadilla"},
            {"foodName":"Cheese Quesadilla", "price":430, "foodType":"Quesadilla"},
       
];
